### ISSUE TITLE
Hexo主题--Bamboo介绍 | Bamboo

### ISSUE THREAD

**Issue by yuang01** [yuang01/yuang01.github.io#3]
https://yuang01.gitee.io/2021/02/08/hexo-theme-bamboo-new/#%E7%BB%93%E8%AF%AD

**Comment by yuang01** [comment]
test

**Comment by Baize0805** [comment]
页面加载的跳转动画在哪里写？

**Comment by yuang01** [comment]
> @Baize0805
> 页面加载的跳转动画在哪里写？

```yaml
preloader:
  on: true
```

**Comment by Baize0805** [comment]
> @yuang01
> > @Baize0805
> > 页面加载的跳转动画在哪里写？
> 
> ```yaml
> preloader:
>   on: true
> ```

找到了，谢谢

**Comment by snowgo** [comment]
dalao,请问为啥我的只有categories页可以播放视频呀，我看到配置里说要屏幕大于920px时才可以，这个该怎么调呢

**Comment by snowgo** [comment]
搞定了，我自己没检查好，感谢dalao

**Comment by xhwl8888** [comment]
你好。背景的那个彩色条咋去掉,就是你一点击就变化那个

**Comment by yuang01** [comment]
> @xhwl8888
> 你好。背景的那个彩色条咋去掉,就是你一点击就变化那个
> 
暂时没有给这个做参数配置，目前只能手动改源码去掉，下个版本会加上这个配置参数

**Comment by symkmk** [comment]
很赞

**Comment by NockingNocking** [comment]
博主您好，能问一下友情链接和关于我页面怎么配置吗？

**Comment by symkmk** [comment]
想问一下怎么支持mermaid插件呢？

**Comment by yuang01** [comment]
> @symkmk
> 想问一下怎么支持mermaid插件呢？

> @symkmk
> 想问一下怎么支持mermaid插件呢？

step1:
```
npm install hexo-filter-mermaid-diagrams  --save
```

step2:

在hexo根目录下找到`_config.yml`,写入以下内容:
```
# mermaid chart
mermaid: ## mermaid url https://github.com/knsv/mermaid
  enable: true  # default true
  version: "8.11.0" # default v7.1.2
  options:  # find more api options from https://github.com/knsv/mermaid/blob/master/src/mermaidAPI.js
    #startOnload: true  // default true
```

step3: 在主题文件夹下找到'footer.ejs'或者'layout.ejs'，加入以下代码:

```
<% if (config.mermaid.enable) { %>
      <script src="https://cdn.bootcdn.net/ajax/libs/mermaid/<%= config.mermaid.version %>/mermaid.min.js"></script>
      <script>
        if (window.mermaid) {
          mermaid.initialize({theme: 'forest'});
        }
      </script>
    <% } %>
```

最后重启服务：
```
hexo clean && hexo s
```

在md中写法
```
graph TD;
    A-->B;
    A-->C;
    B-->D;
    C-->D;
```

**Comment by symkmk** [comment]
你好。上个问题mermaid解决了感谢，还有个问题就是怎么支持图片呢？用了hexo-asset-image安装后的图片显示不正确，<p><img "" class="lazyload placeholder" data-original="/2021/07/13/Netty01-nio/0022.png" src="https://img10.360buyimg.com/ddimg/jfs/t1/157667/29/9156/134350/603c6445Ebbc9cabe/41219c5d36d45072.gif"></p>
src变成了那个一直跑步的小人，求教求教。

**Comment by yuang01** [comment]
不用安装这个插件吧，直接在`_post`同级创建一个`img`文件夹，.md文件中引用直接：
```bash
![Image text](/img/1.jpg)
```
或者，假如你的.md文件叫做`testImg.md`，你可以在`testImg.md`同级创建一个`testImg`文件夹，里面放这个文章的图片，然后:
```bash
![Image text](2.jpg)
```
或者，你直接将图片放到图床上，然后用链接地址，例如：
```bash
![头部导航不透明](https://img10.360buyimg.com/ddimg/jfs/t1/195127/39/6433/1605024/60b98cc8E066b88d4/25ef8fce6fa2966f.png)
```
当然还有其他办法等等，反正我都是放到图床上，然后用链接

**Comment by ly20000814bx** [comment]
那个我的音乐盒一直出不来

**Comment by yuang01** [comment]
> @ly20000814bx
> 那个我的音乐盒一直出不来  

是不是没有参数写的有问题，或者是参数中间有空格，试一下我的：
```yaml
# 音乐
music:
  on: true
  autoHide: true    # hide automaticaly
  server: tencent   #require	music platform: netease, tencent, kugou, xiami, baidu
  type: playlist    #require song, playlist, album, search, artist
  id: 8062553743     #require	song id / playlist id / album id / search keyword
  fixed: true       # 开启吸底模式，建议开启
  autoplay: true   # 是否自动播放, 有些浏览器会禁用自动播放，目前edge可以自动播放
  theme: '#42b983'
  loop: 'all'       # 音频循环播放, 可选值: 'all', 'one', 'none'
  order: 'random'   # 音频循环顺序, 可选值: 'list', 'random'
  preload: 'auto'   # 预加载，可选值: 'none', 'metadata', 'auto'
  volume: 0.7       # 默认音量，请注意播放器会记忆用户设置，用户手动设置音量后默认音量即失效
  listFolded: true  # 列表默认折叠
  hideLrc: false     # 隐藏歌词
```

**Comment by ly20000814bx** [comment]
谢谢 音乐出来了  还有一个地方 就是我顶部栏那里 更多那个位置 只要写 children 就会报错

还有 就是你这个文章下面 这个上一篇 下一篇这里怎么做的

**Comment by yuang01** [comment]
> @ly20000814bx
> 谢谢 音乐出来了  还有一个地方 就是我顶部栏那里 更多那个位置 只要写 children 就会报错
> 
> 还有 就是你这个文章下面 这个上一篇 下一篇这里怎么做的   

你咋写的？

**Comment by leeJustice** [comment]
公告下面的那个推荐文章怎么设置的啊

**Comment by yuang01** [comment]
> @leeJustice
> 公告下面的那个推荐文章怎么设置的啊

```yaml
---
title: Hexo主题--Bamboo介绍
top: true

---
```
使用`top: true`
