### ISSUE TITLE
Bamboo主题-页面功能配置（二） | Bamboo

### ISSUE THREAD

**Issue by yuang01** [yuang01/yuang01.github.io#54]
https://yuang01.gitee.io/post/hexo-theme-bamboo/page/

**Comment by hiyoungshen** [comment]
请问如何修改每一篇博文的背景图片呢？

**Comment by yuang01** [comment]
> @hiyoungshen
> 请问如何修改每一篇博文的背景图片呢？

``` yaml
---
title: Text文本样式标签
date: 2021-02-08 11:35
# swiper: true
categories: 前端
tags: [tag]
# top: true
bgImg: [
    '/img/2.jpg',
    'https://pic2.zhimg.com/80/v2-49362b67989353ff4c8133479f808f32_1440w.jpg?source=1940ef5c',
    'https://pic1.zhimg.com/80/v2-75cce0837ce11c61827e38610feeba85_1440w.jpg?source=1940ef5c'
]
bgImgTransition: 'fade'
img: https://pic4.zhimg.com/v2-8ad0cffeaa7dec5dd1930eebc6ff863f_b.jpg
---

```
